### ISSUE TITLE
Sharding Roadmap

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#190]
### What it is?

As part of the sharding implementation, we need to implement the following high-level tasks.  Each should probably be given its own individual ticket, and each of those tickets *may* be suitable to be broken down further into granular tasks when possible.

Specification: https://github.com/ethereum/sharding/blob/develop/docs/doc.md

#### Protocol changes
- [ ] Ability to swap out underlying trie implementation with binary trie
  - https://github.com/ethereum/research/tree/master/trie_research
  - this will happen in the [`ethereum/py-trie`](https://github.com/ethereum/py-trie) repository.
- [x] Account redesign
  - https://github.com/ethereum/py-evm/issues/191
- [ ] The account access list restriction; see also https://ethresear.ch/t/account-read-write-lists/285
  - https://github.com/ethereum/py-evm/issues/192
- [ ] Account Abstraction
  - https://github.com/ethereum/py-evm/issues/203
- [ ] New transaction format, as in https://ethresear.ch/t/new-transaction-formats-for-sharding/265/1
  - https://github.com/ethereum/py-evm/issues/194
  - depending on #191, #192, #203

#### Refactoring
- [ ] The whole stateless / pure functional redesign
  - #195 Stateless/pure transaction processing
  - #236 Implement `State` object
- [ ] Remove EVM logic from blocks.  Make them *dumb* data containers.

#### Sharding mechanism
- [ ] Shard Manager for watching multiple shards - #196
- [ ] VMC utils #197
- [ ] Set Sharding configuration #246
  - Related to #198
- [ ] VMC Optimization
  - https://github.com/ethereum/sharding/issues/37
- [ ] `Collation` object
- [ ] `Collation` validation
- [ ] Implement shuffling procedure
- [ ] Sharded fork choice rule

### How can it be fixed
Fill this in if you know how to fix it.

**Comment by hwwhww** [comment]
For people who are interested in the concept of basic sharding and stateless client, here's [an overview introduction slide](https://github.com/hwwhww/eth-research/blob/master/sharding/slides/Ethereum_Sharding_Concept_20171203_Shenzhen.pdf).

**Comment by hwwhww** [comment]
Sharding doc: https://github.com/ethereum/sharding/blob/develop/docs/doc.md

**Comment by mhchia** [comment]
@pipermerriam 
Just want to confirm. Are we also going to implement a full node in `py-evm` recently?
If we are, is there anything which is currently not in `pyevm` and is needed to be implemented? and how should we start?
Thank you!

**Comment by pipermerriam** [comment]
cc @gsalgado 

I believe that @gsalgado has started work on that, or is going to start work on it next.

**Comment by gsalgado** [comment]
Yep, I've started implementing the ETH protocol in https://github.com/gsalgado/py-evm/tree/eth63﻿ and https://github.com/gsalgado/py-trie/tree/trie-sync﻿ has some trie-related code we're going to need to download the state as part of a fast-sync

**Comment by mhchia** [comment]
That's great! Then I think I can work on the other parts.
Just think it's cool that the urls seem to be processed as UTF-8 instead of ASCII, so they don't work when we click on them.

**Comment by gsalgado** [comment]
Looks like the URLs ended up with some non-printable trailing characters when I originally pasted them; I've removed that and they work now

**Comment by pipermerriam** [comment]
@gsalgado I found this recently in hypothesis for doing deterministic randomness generation for tests using the standard lib `random` module.  Might be a good standard to adopt so that when we are using randomeness in tests like the utility function you're using in your py-trie branch for generating a random trie, we can reproduce failures.

https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.random_module

**Comment by hwwhww** [comment]
Deprecated. :'( Will add a new one.
