### ISSUE TITLE
EOFv1 Checklist

### ISSUE THREAD

**Issue by fselmo** [ethereum/py-evm#2089]
Consult the [EOFv1 checklist](https://notes.ethereum.org/@ipsilon/eof1-checklist#Specification--Tests) for specifics.
---

This is the main tracking issue for the EOFv1 checklist. If you have interest in one of the below tasks, don't hesitate to mention it here, open a PR, and link it in this issue. Drafts are welcome. We can edit this description and link the PR to the respective EIP(s) within its scope to track progress.

- [ ] [EIP-3860](https://eips.ethereum.org/EIPS/eip-3860): Limit and meter initcode (EOF prerequisite) [history](https://github.com/ethereum/EIPs/commits/master/EIPS/eip-3860.md)
- [ ] [EIP-3540](https://eips.ethereum.org/EIPS/eip-3540): EOF - EVM Object Format v1 [history](https://github.com/ethereum/EIPs/commits/master/EIPS/eip-3540.md)
- [ ] [EIP-3670](https://eips.ethereum.org/EIPS/eip-3670): EOF - Code Validation [history](https://github.com/ethereum/EIPs/commits/master/EIPS/eip-3670.md)
- [ ] [EIP-4200](https://eips.ethereum.org/EIPS/eip-4200): EOF - Static relative jumps [history](https://github.com/ethereum/EIPs/commits/master/EIPS/eip-4200.md)
- [ ] [EIP-4750](https://eips.ethereum.org/EIPS/eip-4750): EOF - Functions [history](https://github.com/ethereum/EIPs/commits/master/EIPS/eip-4750.md)
- [ ] [EIP-5450](https://eips.ethereum.org/EIPS/eip-5450): EOF - Stack Validation [history](https://github.com/ethereum/EIPs/commits/master/EIPS/eip-5450.md)
