### ISSUE TITLE
Bnb

### ISSUE THREAD

**Issue by Carlo0704** [ethereum/py-evm#2180]
https://github.com/etherscan/ethvalidate/issues/121
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/py-evm/pull/1709
- [ ] https://github.com/ethereum/py-evm/issues/2177
- [ ] https://github.com/ethereum/py-evm/issues/1941
- [ ] https://github.com/ethereum/py-evm/issues/2127
```

**Comment by Carlo0704** [comment]
> https://github.com/etherscan/ethvalidate/issues/121
