### ISSUE TITLE
Trinity Alpha Release Checklist

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#712]
### Definition of what's needed for alpha release

All of the following need to work for our alpha release.

- [ ] full sync
  - [ ] `$ trinity`
    - [ ] initializes databases and runs full sync on main chain
    - [ ] starts with fast sync if local head is older than 24h, then switches to regular sync. otherwise starts with regular sync
  - [ ] `$ trinity --ropsten`
    - [ ] same as previous but on the ropsten network.
- [x] light sync
  - [x] `$ trinity --light`
    - [x] initializes separate light database, syncs header chain
- [ ] JSON-RPC
    - [ ] JSON-RPC server over IPC socket should be run in both full and light modes.  
    - [ ] All standard `eth_` endpoints should work **or** explicitely be stubbed out returning an error response indicating that it hasn't yet been implemented.
- [ ] console
  - [ ] `$ trinity attach`: https://github.com/ethereum/py-evm/issues/715
    - [ ] Attaches to a running trinity node, exposes a python REPL with a Web3 instance available in the context.

**Comment by carver** [comment]
> `trinity --light`

Just for completeness, I guess we should add `trinity --light --ropsten` too.

> All standard `eth_` endpoints.

See https://github.com/ethereum/py-evm/issues/612 for a jump-start on the read-only ones.

>  `trinity attach` - Attaches to a running trinity node

Are you thinking some system introspection to find the running trinity process and ask it where the IPC file is? Even that leaves some ambiguity if two processes are running. The easiest thing for alpha is probably to `trinity attach '/path/to/jsonrpc.ipc'`, although if that's the end goal, then we might as well add a command like it to web3.py: `web3py attach <ipc_file>`, and support all nodes out of the box.

**Comment by carver** [comment]
I'm starting to take a look at how to get jsonrpc working on a light client. Will take a bit of time to get acquainted with the networking code.

**Comment by pipermerriam** [comment]
> Are you thinking some system introspection to find the running trinity process and ask it where the IPC file is?

- `trinity attach`
  - looks for `jsonrpc.ipc` *all* chain folders found in the `$TRINITY_HOME`.  
    - If exactly 1 is found, displays what IPC socket it's connecting to and launches console.
    - if 0 or `>1` are found, displays appropriate error.
- `trinity attach `/path/to/jsonrpc.ipc`
  - connect to the specified socket.
